package xyz.stylianosgakis.shape.android.core.theme

import androidx.compose.ui.graphics.Color

// https://www.canva.com/colors/color-wheel/ with #6C947F and 2 Analogous colors, #7F6C94 and #947F6C.
// https://m3.material.io/theme-builder#/custom with #0080FF, #0000FF, #00FFFF, the colors gotten from canva
@Suppress("unused")
private val seed = Color(0xFF6C947F)

val light_primary = Color(0xFF006C4B)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF8AF8C5)
val light_onPrimaryContainer = Color(0xFF002114)
val light_secondary = Color(0xFF724C9F)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFEEDBFF)
val light_onSecondaryContainer = Color(0xFF2A0053)
val light_tertiary = Color(0xFF8A5100)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFDCBD)
val light_onTertiaryContainer = Color(0xFF2C1600)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFBFDF9)
val light_onBackground = Color(0xFF191C1A)
val light_surface = Color(0xFFFBFDF9)
val light_onSurface = Color(0xFF191C1A)
val light_surfaceVariant = Color(0xFFDCE5DD)
val light_onSurfaceVariant = Color(0xFF404943)
val light_outline = Color(0xFF707973)
val light_inverseOnSurface = Color(0xFFEFF1ED)
val light_inverseSurface = Color(0xFF2E312F)
val light_inversePrimary = Color(0xFF6DDBAA)

@Suppress("unused")
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF006C4B)

val dark_primary = Color(0xFF6DDBAA)
val dark_onPrimary = Color(0xFF003825)
val dark_primaryContainer = Color(0xFF005137)
val dark_onPrimaryContainer = Color(0xFF8AF8C5)
val dark_secondary = Color(0xFFDAB9FF)
val dark_onSecondary = Color(0xFF411B6D)
val dark_secondaryContainer = Color(0xFF593485)
val dark_onSecondaryContainer = Color(0xFFEEDBFF)
val dark_tertiary = Color(0xFFFFB86E)
val dark_onTertiary = Color(0xFF492900)
val dark_tertiaryContainer = Color(0xFF693C00)
val dark_onTertiaryContainer = Color(0xFFFFDCBD)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1A)
val dark_onBackground = Color(0xFFE1E3DF)
val dark_surface = Color(0xFF191C1A)
val dark_onSurface = Color(0xFFE1E3DF)
val dark_surfaceVariant = Color(0xFF404943)
val dark_onSurfaceVariant = Color(0xFFBFC9C1)
val dark_outline = Color(0xFF8A938C)
val dark_inverseOnSurface = Color(0xFF191C1A)
val dark_inverseSurface = Color(0xFFE1E3DF)
val dark_inversePrimary = Color(0xFF006C4B)

@Suppress("unused")
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF6DDBAA)
